//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace AccountingTransactionService.Service_References.RequisitesResolverService {
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatorRequisite", Namespace="http://schemas.datacontract.org/2004/07/OperatorRequisitesResolver.App_Code.Commu" +
        "nication")]
    [Serializable()]
    public partial class OperatorRequisite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private string AccountField;
        
        [OptionalField()]
        private string BankAccountField;
        
        [OptionalField()]
        private string BankBIKField;
        
        [OptionalField()]
        private string BankCorAccountField;
        
        [OptionalField()]
        private string BankNameField;
        
        [OptionalField()]
        private string FilterField;
        
        [OptionalField()]
        private string INNField;
        
        [OptionalField()]
        private string KPPField;
        
        [OptionalField()]
        private long OperatorIdField;
        
        [OptionalField()]
        private string OperatorNameField;
        
        [OptionalField()]
        private string OrganizationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccount {
            get {
                return this.BankAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountField, value) != true)) {
                    this.BankAccountField = value;
                    this.RaisePropertyChanged("BankAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankBIK {
            get {
                return this.BankBIKField;
            }
            set {
                if ((object.ReferenceEquals(this.BankBIKField, value) != true)) {
                    this.BankBIKField = value;
                    this.RaisePropertyChanged("BankBIK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankCorAccount {
            get {
                return this.BankCorAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.BankCorAccountField, value) != true)) {
                    this.BankCorAccountField = value;
                    this.RaisePropertyChanged("BankCorAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filter {
            get {
                return this.FilterField;
            }
            set {
                if ((object.ReferenceEquals(this.FilterField, value) != true)) {
                    this.FilterField = value;
                    this.RaisePropertyChanged("Filter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string INN {
            get {
                return this.INNField;
            }
            set {
                if ((object.ReferenceEquals(this.INNField, value) != true)) {
                    this.INNField = value;
                    this.RaisePropertyChanged("INN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KPP {
            get {
                return this.KPPField;
            }
            set {
                if ((object.ReferenceEquals(this.KPPField, value) != true)) {
                    this.KPPField = value;
                    this.RaisePropertyChanged("KPP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OperatorId {
            get {
                return this.OperatorIdField;
            }
            set {
                if ((this.OperatorIdField.Equals(value) != true)) {
                    this.OperatorIdField = value;
                    this.RaisePropertyChanged("OperatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorName {
            get {
                return this.OperatorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorNameField, value) != true)) {
                    this.OperatorNameField = value;
                    this.RaisePropertyChanged("OperatorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RequisitesResolverService.IOperatorRequisitesResolverService")]
    public interface IOperatorRequisitesResolverService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperatorRequisitesResolverService/GetOperatorRequisite", ReplyAction="http://tempuri.org/IOperatorRequisitesResolverService/GetOperatorRequisiteRespons" +
            "e")]
        OperatorRequisite GetOperatorRequisite(long operatorId, string paramsString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperatorRequisitesResolverServiceChannel : IOperatorRequisitesResolverService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperatorRequisitesResolverServiceClient : System.ServiceModel.ClientBase<IOperatorRequisitesResolverService>, IOperatorRequisitesResolverService, IDisposable
    {
        
        public OperatorRequisitesResolverServiceClient() {
        }
        
        public OperatorRequisitesResolverServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperatorRequisitesResolverServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperatorRequisitesResolverServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperatorRequisitesResolverServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OperatorRequisite GetOperatorRequisite(long operatorId, string paramsString) {
            return base.Channel.GetOperatorRequisite(operatorId, paramsString);
        }

        public void Dispose()
        {
            throw new NotImplementedException();
        }
    }
}
